#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to Christof's needs...
if [[ -s "$HOME}/dev/etc/dotzshrc" ]]; then
  source "$HOME/dev/etc/dotzshrc"
fi
